version: 0.1

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - grails prod war
      - unzip build/libs/Kllect_production.war -d build/libs/Kllect_production
      - mv build/libs/Kllect_production ./
artifacts:
  files:
    - Kllect_production/**/*