---
#grails:
#    mongodb:
#        connectionString: "mongodb://kllect_app:VQ4-QmD-TE2-CMq@ds025449.mlab.com:25449/kllect"

environments:
    development:
        grails:
            mongodb:
                connectionString: "mongodb://kllect_app:JM9MQWh9xwRbeKD@ds049456.mlab.com:49456/tagged-dev2"
    test:
        grails:
            mongodb:
                connectionString: "mongodb://kllect_app:JM9MQWh9xwRbeKD@ds049456.mlab.com:49456/tagged-dev2"
    production:
        grails:
            mongodb:
                connectionString: '${JDBC_CONNECTION_STRING}'


---
---
grails:
    profile: rest-api
    codegen:
        defaultPackage: kllect
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
